on:
  schedule:
    - cron: '30 * * * *'

env:
  URL: https://micro-acquisition.alpha.canada.ca
  FILENAME: (date '+%Y_%m_%d')_report.yaml
  CONFIG: config.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
