on:
  schedule:
    - cron: '30 * * * *'

env:
  URL: https://micro-acquisition.alpha.canada.ca

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: Link Snitch
        uses: victoriadrake/link-snitch@v1.0.0
